spring:
  application:
    name: Spring-ai

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:latest

    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
         # model: gemini-3.6-flash     # Fast   Higher Intelligence  Complex tasks
          model: gemini-3.5-flash-lite      # very fast, good intelligence, learning and testing
          options:
            temperature: 0.8


    model:
      chat: google-genai


logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

