spring:
  application:
    name: Spring-ai

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:latest

    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-3.6-flash

    model:
      chat: google-genai

