spring:
  application:
    name: Spring-ai

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:latest

    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.9
      embedding:
        options:
          model: text-embedding-3-small


    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
         # model: gemini-3.6-flash     # Fast   Higher Intelligence  Complex tasks
          model: gemini-3.5-flash-lite      # very fast, good intelligence, learning and testing
          options:
            temperature: 0.8


    model:
      #chat: openai
      chat: ollama


logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

